path: /content/drive/MyDrive/CNN-CV Lesson/Data Set and NB/Plate Reading/data/character_dataset

train: ./images/train
val: ./images/test
test: ./images/valid

nc: 31
names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z']
